name: Deploy Laravel + React

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          script: |
            # Laravel backend deployment
            cd /var/www/html/4g_api_project/backend
            git pull origin main
            composer install --no-interaction --prefer-dist
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache

            # React frontend build
            cd /var/www/html/4g_api_project/frontend
            git pull origin main
            npm install
            npm run build

            sudo systemctl reload apache2

